### ISSUE TITLE
Pet Battle Scripts is completely missing

### ISSUE THREAD

**Issue by Gamara747** [axc450/pbs#30]
The files are installed. I've uninstalled and reinstalled many times. I can make teams but there are no tabs, no right click to make notes or write a script. The buttons for the hat and the sausage are missing. There's no "target" or save. Any suggestions

**Comment by bloerwald** [comment]
This really sounds like an issue with Rematch rather than this addon. We don’t touch notes, hat, sausage, target and save buttons. 

To narrow down the issue: do these features work with the scripts addon disabled? Did you try reinstalling Rematch and checking that it is properly enabled? Do other Rematch features work? Are there any Lua errors?

**Comment by Gamara747** [comment]
Thank you. That was it exactly. Rematch was disabled. All better and all my teams are back.
