### ISSUE TITLE
Iron Starlette's self.aura(Wind-Up:459) not recognised with ID in the selectors

### ISSUE THREAD

**Issue by morgan35543** [axc450/pbs#76]
When the Iron Starlette's Wind-Up aura is present, if I include the ID in the selectors, the conditional fails as it doesn't see the aura.

Ability: https://www.wowhead.com/pet-ability=459/wind-up

This works:
`test(Without ID) [!self.aura(Wind-Up).exists]`

This fails:
`test(With ID) [!self.aura(Wind-Up:459).exists]`

Full script against Glitterdust in Ardenweald:
```
quit [ally(Stormborne Whelpling:1721).dead & enemy(Slugger:3000).active]
change(Iron Starlette:1387) [enemy(Slugger:3000).dead]
change(Chrominius:1152) [ally(Iron Starlette:1387).dead]

if [self.is(Stormborne Whelpling:1721)]
  use(Tail Sweep:122) [round >= 3]
  use(Call Lightning:204)
  use(Arcane Storm:589)
endif
if [self.is(Iron Starlette:1387)]
  use(Wind-Up:459) [!self.aura(Wind-Up).exists] -- Problematic line
  use(Supercharge:208) [enemy.is(Runehoof:3001)]
  use(Wind-Up:459)
endif
if [self.is(Chrominius:1152)]
  use(Howl:362)
  use(Surge of Power:593)
  use(Arcane Explosion:299)
endif
```

**Comment by bloerwald** [comment]
Pet battle abilities giving a buff apply a *different* ability for the buff. 459 applies the buff, but the buff itself is 458. If you require the buff 459 to be up, it will never be since there is no buff 459. When you edit the script in fight, the buff ID will show in auto-complete *if it is up*. It only shows things seen in battle, which might be a thing we should change…

If you use `[ !self.aura(458).exists ]`, it will work.

You can see the two different abilities at e.g.  https://wago.tools/db2/BattlePetAbility?filter[Name_lang]=wind-up.

**Comment by morgan35543** [comment]
Ah wow okay, thanks for the link to that wago tool also
